sudo: required
services:
  - docker

before_install:
  - docker build -t stere4th/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stere4th/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-496462037489"
  bucket_path: "docker-test"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

